[build-system]
requires = [
    "setuptools>=80.9.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "docassemble.ALKilnSetup"
version = "2.0.0"
description = "A docassemble extension for setting up the AssemblyLine automated integrated testing framework for your docassemble package repository."
readme = "README.md"
authors = [
    { name = "", email = "example@example.com" },
]
dependencies = [
    "PyGithub>=2.9.1",
    "PyNaCl>=1.6.2",
    "docassemble.ALToolbox @ git+https://github.com/SuffolkLITLab/docassemble-ALToolbox.git@main",
    "requests>=2.32.5",
]
license = "MIT"
license-files = [
    "LICENSE",
]

[project.urls]
Homepage = "https://docassemble.org"

[tool.setuptools.packages.find]
where = [
    ".",
]
