name: DA Build
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: SuffolkLITLab/ALActions/da_build@main
        with:
          ignore-urls: |
            https://github.com/$
            https://github.com/${
            https://github.com/organizations/${
            https://github.com/TheLawFantastic/docassemble-GreatForm
            https://github.com/TheLawFantastic/docassemble-GreatForm**
            https://github.com/owner_name/repo_name
            https://github.com/owner_name/repo_name**
            https://legal-dev.example.org
            https://legal-dev.example.org**
